import { Text, View, StyleSheet } from 'react-native';

export default function AboutScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>About the App</Text>
      <Text style={styles.description}>
        This app is designed as an Image Descriptor, allowing users to upload images and receive detailed descriptions generated by AI.
      </Text>
      <Text style={styles.developers}>
        Developed by: Abdullah and Faisal
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#25292e',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20, // Added padding for better layout
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 20,
  },
  description: {
    fontSize: 16,
    color: '#fff',
    textAlign: 'center',
    marginBottom: 20,
  },
  developers: {
    fontSize: 16,
    color: '#fff',
  },
});
